apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-app
  labels:
    app: nginx-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-web-app
  template:
    metadata:
      labels:
        app: nginx-web-app
    spec:
      containers:
        - name: nginx-web-container
          image: kiran22222/nginx-web-app-rk
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
