apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
spec:
  type: NodePort  # For Minikube; change to LoadBalancer for EKS
  selector:
    app: nginx-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30036
